name: Vue.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build
      run: |
        echo "Setting up environment variables"
        
        echo "VUE_APP_API_ROOT=${{ vars.API_ROOT }}" >> .env
        echo "VUE_APP_ROOT=${{ vars.APP_ROOT }}" >> .env
        cat .env
        npm run build

    - name: Deploy to Server
      run: |
        rsync -avz -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" dist/ ${{ vars.SSH_DEPLOY_USER }}@${{ vars.SSH_DEPLOY_IP }}:/var/www/portfolio/bl-studio
